# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
    - 'src/main/resources/*.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 初始化JDK16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: 开始打包
      run: |
        mvn -B clean package -Dmaven.test.skip=true --file pom.xml
        cd ./target
        java -jar --enable-preview -Xms512m -Xmx7g ./*.jar
    
    - name: 上传结果
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: finder-result
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/finder
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
        # Duration after which artifact will expire in days. 0 means using default retention.Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 90
      
